services:
  streamlit:
    image: tonykip/streamlit-app:latest
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    environment:
      - ENV=development
      - DEBUG=true
      - LOG_LEVEL=debug
    networks:
      - app-network
    command: streamlit run streamlit_app.py --server.address=0.0.0.0
    working_dir: /app

networks:
  app-network:
    driver: bridge
